/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jimi_jmlog_JMLogJni */

#ifndef _Included_com_jimi_jmlog_JMLogJni
#define _Included_com_jimi_jmlog_JMLogJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jimi_jmlog_JMLogJni
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jimi_jmlog_JMLogJni_Init
  (JNIEnv *, jclass);

/*
 * Class:     com_jimi_jmlog_JMLogJni
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jimi_jmlog_JMLogJni_Release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
