/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eafy_zjlog_ZJLogJni */

#ifndef _Included_com_eafy_zjlog_ZJLogJni
#define _Included_com_eafy_zjlog_ZJLogJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eafy_zjlog_ZJLogJni
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eafy_zjlog_ZJLogJni_Init
  (JNIEnv *, jclass);

/*
 * Class:     com_eafy_zjlog_ZJLogJni
 * Method:    Release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eafy_zjlog_ZJLogJni_Release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
