/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eafy_zjlog_ZJLogJni */
#include "CPrintfLog.h"

#ifndef _Included_com_eafy_zjlog_ZJLogJni
#define _Included_com_eafy_zjlog_ZJLogJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eafy_zjlog_ZJLogJni
 * Method:    OpenLog
 * Signature: (Z)J
 */
JNIEXPORT void JNICALL Java_com_eafy_zjlog_ZJLogJni_OpenLog
  (JNIEnv *, jclass, jboolean);


#ifdef __cplusplus
}
#endif
#endif
